# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2025, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.8\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-08-10 15:08+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: zh_TW\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../../../library/asyncio-task.rst:6
msgid "Coroutines and Tasks"
msgstr ""

#: ../../../library/asyncio-task.rst:8
msgid ""
"This section outlines high-level asyncio APIs to work with coroutines and "
"Tasks."
msgstr ""

#: ../../../library/asyncio-task.rst:19 ../../../library/asyncio-task.rst:121
msgid "Coroutines"
msgstr ""

#: ../../../library/asyncio-task.rst:21
msgid ""
":term:`Coroutines <coroutine>` declared with the async/await syntax is the "
"preferred way of writing asyncio applications.  For example, the following "
"snippet of code (requires Python 3.7+) prints \"hello\", waits 1 second, and "
"then prints \"world\"::"
msgstr ""

#: ../../../library/asyncio-task.rst:26
msgid ""
">>> import asyncio\n"
"\n"
">>> async def main():\n"
"...     print('hello')\n"
"...     await asyncio.sleep(1)\n"
"...     print('world')\n"
"\n"
">>> asyncio.run(main())\n"
"hello\n"
"world"
msgstr ""

#: ../../../library/asyncio-task.rst:37
msgid ""
"Note that simply calling a coroutine will not schedule it to be executed::"
msgstr ""

#: ../../../library/asyncio-task.rst:40
msgid ""
">>> main()\n"
"<coroutine object main at 0x1053bb7c8>"
msgstr ""

#: ../../../library/asyncio-task.rst:43
msgid "To actually run a coroutine, asyncio provides three main mechanisms:"
msgstr ""

#: ../../../library/asyncio-task.rst:45
msgid ""
"The :func:`asyncio.run` function to run the top-level entry point \"main()\" "
"function (see the above example.)"
msgstr ""

#: ../../../library/asyncio-task.rst:48
msgid ""
"Awaiting on a coroutine.  The following snippet of code will print \"hello\" "
"after waiting for 1 second, and then print \"world\" after waiting for "
"*another* 2 seconds::"
msgstr ""

#: ../../../library/asyncio-task.rst:52
msgid ""
"import asyncio\n"
"import time\n"
"\n"
"async def say_after(delay, what):\n"
"    await asyncio.sleep(delay)\n"
"    print(what)\n"
"\n"
"async def main():\n"
"    print(f\"started at {time.strftime('%X')}\")\n"
"\n"
"    await say_after(1, 'hello')\n"
"    await say_after(2, 'world')\n"
"\n"
"    print(f\"finished at {time.strftime('%X')}\")\n"
"\n"
"asyncio.run(main())"
msgstr ""

#: ../../../library/asyncio-task.rst:69
msgid "Expected output::"
msgstr ""

#: ../../../library/asyncio-task.rst:71
msgid ""
"started at 17:13:52\n"
"hello\n"
"world\n"
"finished at 17:13:55"
msgstr ""

#: ../../../library/asyncio-task.rst:76
msgid ""
"The :func:`asyncio.create_task` function to run coroutines concurrently as "
"asyncio :class:`Tasks <Task>`."
msgstr ""

#: ../../../library/asyncio-task.rst:79
msgid ""
"Let's modify the above example and run two ``say_after`` coroutines "
"*concurrently*::"
msgstr ""

#: ../../../library/asyncio-task.rst:82
msgid ""
"async def main():\n"
"    task1 = asyncio.create_task(\n"
"        say_after(1, 'hello'))\n"
"\n"
"    task2 = asyncio.create_task(\n"
"        say_after(2, 'world'))\n"
"\n"
"    print(f\"started at {time.strftime('%X')}\")\n"
"\n"
"    # Wait until both tasks are completed (should take\n"
"    # around 2 seconds.)\n"
"    await task1\n"
"    await task2\n"
"\n"
"    print(f\"finished at {time.strftime('%X')}\")"
msgstr ""

#: ../../../library/asyncio-task.rst:98
msgid ""
"Note that expected output now shows that the snippet runs 1 second faster "
"than before::"
msgstr ""

#: ../../../library/asyncio-task.rst:101
msgid ""
"started at 17:14:32\n"
"hello\n"
"world\n"
"finished at 17:14:34"
msgstr ""

#: ../../../library/asyncio-task.rst:110
msgid "Awaitables"
msgstr ""

#: ../../../library/asyncio-task.rst:112
msgid ""
"We say that an object is an **awaitable** object if it can be used in an :"
"keyword:`await` expression.  Many asyncio APIs are designed to accept "
"awaitables."
msgstr ""

#: ../../../library/asyncio-task.rst:116
msgid ""
"There are three main types of *awaitable* objects: **coroutines**, "
"**Tasks**, and **Futures**."
msgstr ""

#: ../../../library/asyncio-task.rst:122
msgid ""
"Python coroutines are *awaitables* and therefore can be awaited from other "
"coroutines::"
msgstr ""

#: ../../../library/asyncio-task.rst:125
msgid ""
"import asyncio\n"
"\n"
"async def nested():\n"
"    return 42\n"
"\n"
"async def main():\n"
"    # Nothing happens if we just call \"nested()\".\n"
"    # A coroutine object is created but not awaited,\n"
"    # so it *won't run at all*.\n"
"    nested()\n"
"\n"
"    # Let's do it differently now and await it:\n"
"    print(await nested())  # will print \"42\".\n"
"\n"
"asyncio.run(main())"
msgstr ""

#: ../../../library/asyncio-task.rst:143
msgid ""
"In this documentation the term \"coroutine\" can be used for two closely "
"related concepts:"
msgstr ""

#: ../../../library/asyncio-task.rst:146
msgid "a *coroutine function*: an :keyword:`async def` function;"
msgstr ""

#: ../../../library/asyncio-task.rst:148
msgid ""
"a *coroutine object*: an object returned by calling a *coroutine function*."
msgstr ""

#: ../../../library/asyncio-task.rst:151
msgid ""
"asyncio also supports legacy :ref:`generator-based "
"<asyncio_generator_based_coro>` coroutines."
msgstr ""

#: ../../../library/asyncio-task.rst:156
msgid "Tasks"
msgstr ""

#: ../../../library/asyncio-task.rst:157
msgid "*Tasks* are used to schedule coroutines *concurrently*."
msgstr ""

#: ../../../library/asyncio-task.rst:159
msgid ""
"When a coroutine is wrapped into a *Task* with functions like :func:`asyncio."
"create_task` the coroutine is automatically scheduled to run soon::"
msgstr ""

#: ../../../library/asyncio-task.rst:163
msgid ""
"import asyncio\n"
"\n"
"async def nested():\n"
"    return 42\n"
"\n"
"async def main():\n"
"    # Schedule nested() to run soon concurrently\n"
"    # with \"main()\".\n"
"    task = asyncio.create_task(nested())\n"
"\n"
"    # \"task\" can now be used to cancel \"nested()\", or\n"
"    # can simply be awaited to wait until it is complete:\n"
"    await task\n"
"\n"
"asyncio.run(main())"
msgstr ""

#: ../../../library/asyncio-task.rst:181
msgid "Futures"
msgstr ""

#: ../../../library/asyncio-task.rst:182
msgid ""
"A :class:`Future` is a special **low-level** awaitable object that "
"represents an **eventual result** of an asynchronous operation."
msgstr ""

#: ../../../library/asyncio-task.rst:185
msgid ""
"When a Future object is *awaited* it means that the coroutine will wait "
"until the Future is resolved in some other place."
msgstr ""

#: ../../../library/asyncio-task.rst:188
msgid ""
"Future objects in asyncio are needed to allow callback-based code to be used "
"with async/await."
msgstr ""

#: ../../../library/asyncio-task.rst:191
msgid ""
"Normally **there is no need** to create Future objects at the application "
"level code."
msgstr ""

#: ../../../library/asyncio-task.rst:194
msgid ""
"Future objects, sometimes exposed by libraries and some asyncio APIs, can be "
"awaited::"
msgstr ""

#: ../../../library/asyncio-task.rst:197
msgid ""
"async def main():\n"
"    await function_that_returns_a_future_object()\n"
"\n"
"    # this is also valid:\n"
"    await asyncio.gather(\n"
"        function_that_returns_a_future_object(),\n"
"        some_python_coroutine()\n"
"    )"
msgstr ""

#: ../../../library/asyncio-task.rst:206
msgid ""
"A good example of a low-level function that returns a Future object is :meth:"
"`loop.run_in_executor`."
msgstr ""

#: ../../../library/asyncio-task.rst:211
msgid "Running an asyncio Program"
msgstr ""

#: ../../../library/asyncio-task.rst:215
msgid "Execute the :term:`coroutine` *coro* and return the result."
msgstr ""

#: ../../../library/asyncio-task.rst:217
msgid ""
"This function runs the passed coroutine, taking care of managing the asyncio "
"event loop and *finalizing asynchronous generators*."
msgstr ""

#: ../../../library/asyncio-task.rst:221
msgid ""
"This function cannot be called when another asyncio event loop is running in "
"the same thread."
msgstr ""

#: ../../../library/asyncio-task.rst:224
msgid "If *debug* is ``True``, the event loop will be run in debug mode."
msgstr ""

#: ../../../library/asyncio-task.rst:226
msgid ""
"This function always creates a new event loop and closes it at the end.  It "
"should be used as a main entry point for asyncio programs, and should "
"ideally only be called once."
msgstr ""

#: ../../../library/asyncio-task.rst:230 ../../../library/asyncio-task.rst:354
#: ../../../library/asyncio-task.rst:471 ../../../library/asyncio-task.rst:601
msgid "Example::"
msgstr ""

#: ../../../library/asyncio-task.rst:232
msgid ""
"async def main():\n"
"    await asyncio.sleep(1)\n"
"    print('hello')\n"
"\n"
"asyncio.run(main())"
msgstr ""

#: ../../../library/asyncio-task.rst:242
msgid ""
"The source code for ``asyncio.run()`` can be found in :source:`Lib/asyncio/"
"runners.py`."
msgstr ""

#: ../../../library/asyncio-task.rst:246
msgid "Creating Tasks"
msgstr ""

#: ../../../library/asyncio-task.rst:250
msgid ""
"Wrap the *coro* :ref:`coroutine <coroutine>` into a :class:`Task` and "
"schedule its execution.  Return the Task object."
msgstr ""

#: ../../../library/asyncio-task.rst:253
msgid ""
"If *name* is not ``None``, it is set as the name of the task using :meth:"
"`Task.set_name`."
msgstr ""

#: ../../../library/asyncio-task.rst:256
msgid ""
"The task is executed in the loop returned by :func:`get_running_loop`, :exc:"
"`RuntimeError` is raised if there is no running loop in current thread."
msgstr ""

#: ../../../library/asyncio-task.rst:260
msgid ""
"This function has been **added in Python 3.7**.  Prior to Python 3.7, the "
"low-level :func:`asyncio.ensure_future` function can be used instead::"
msgstr ""

#: ../../../library/asyncio-task.rst:264
msgid ""
"async def coro():\n"
"    ...\n"
"\n"
"# In Python 3.7+\n"
"task = asyncio.create_task(coro())\n"
"...\n"
"\n"
"# This works in all Python versions but is less readable\n"
"task = asyncio.ensure_future(coro())\n"
"..."
msgstr ""

#: ../../../library/asyncio-task.rst:277 ../../../library/asyncio-task.rst:724
msgid "Added the ``name`` parameter."
msgstr ""

#: ../../../library/asyncio-task.rst:282
msgid "Sleeping"
msgstr ""

#: ../../../library/asyncio-task.rst:286
msgid "Block for *delay* seconds."
msgstr ""

#: ../../../library/asyncio-task.rst:288
msgid ""
"If *result* is provided, it is returned to the caller when the coroutine "
"completes."
msgstr ""

#: ../../../library/asyncio-task.rst:291
msgid ""
"``sleep()`` always suspends the current task, allowing other tasks to run."
msgstr ""

#: ../../../library/asyncio-task.rst:296 ../../../library/asyncio-task.rst:351
#: ../../../library/asyncio-task.rst:438 ../../../library/asyncio-task.rst:468
#: ../../../library/asyncio-task.rst:553 ../../../library/asyncio-task.rst:600
#: ../../../library/asyncio-task.rst:729
msgid "The *loop* parameter."
msgstr ""

#: ../../../library/asyncio-task.rst:299
msgid ""
"Example of coroutine displaying the current date every second for 5 seconds::"
msgstr ""

#: ../../../library/asyncio-task.rst:302
msgid ""
"import asyncio\n"
"import datetime\n"
"\n"
"async def display_date():\n"
"    loop = asyncio.get_running_loop()\n"
"    end_time = loop.time() + 5.0\n"
"    while True:\n"
"        print(datetime.datetime.now())\n"
"        if (loop.time() + 1.0) >= end_time:\n"
"            break\n"
"        await asyncio.sleep(1)\n"
"\n"
"asyncio.run(display_date())"
msgstr ""

#: ../../../library/asyncio-task.rst:318
msgid "Running Tasks Concurrently"
msgstr ""

#: ../../../library/asyncio-task.rst:322
msgid ""
"Run :ref:`awaitable objects <asyncio-awaitables>` in the *aws* sequence "
"*concurrently*."
msgstr ""

#: ../../../library/asyncio-task.rst:325
msgid ""
"If any awaitable in *aws* is a coroutine, it is automatically scheduled as a "
"Task."
msgstr ""

#: ../../../library/asyncio-task.rst:328
msgid ""
"If all awaitables are completed successfully, the result is an aggregate "
"list of returned values.  The order of result values corresponds to the "
"order of awaitables in *aws*."
msgstr ""

#: ../../../library/asyncio-task.rst:332
msgid ""
"If *return_exceptions* is ``False`` (default), the first raised exception is "
"immediately propagated to the task that awaits on ``gather()``.  Other "
"awaitables in the *aws* sequence **won't be cancelled** and will continue to "
"run."
msgstr ""

#: ../../../library/asyncio-task.rst:337
msgid ""
"If *return_exceptions* is ``True``, exceptions are treated the same as "
"successful results, and aggregated in the result list."
msgstr ""

#: ../../../library/asyncio-task.rst:340
msgid ""
"If ``gather()`` is *cancelled*, all submitted awaitables (that have not "
"completed yet) are also *cancelled*."
msgstr ""

#: ../../../library/asyncio-task.rst:343
msgid ""
"If any Task or Future from the *aws* sequence is *cancelled*, it is treated "
"as if it raised :exc:`CancelledError` -- the ``gather()`` call is **not** "
"cancelled in this case.  This is to prevent the cancellation of one "
"submitted Task/Future to cause other Tasks/Futures to be cancelled."
msgstr ""

#: ../../../library/asyncio-task.rst:356
msgid ""
"import asyncio\n"
"\n"
"async def factorial(name, number):\n"
"    f = 1\n"
"    for i in range(2, number + 1):\n"
"        print(f\"Task {name}: Compute factorial({i})...\")\n"
"        await asyncio.sleep(1)\n"
"        f *= i\n"
"    print(f\"Task {name}: factorial({number}) = {f}\")\n"
"\n"
"async def main():\n"
"    # Schedule three calls *concurrently*:\n"
"    await asyncio.gather(\n"
"        factorial(\"A\", 2),\n"
"        factorial(\"B\", 3),\n"
"        factorial(\"C\", 4),\n"
"    )\n"
"\n"
"asyncio.run(main())\n"
"\n"
"# Expected output:\n"
"#\n"
"#     Task A: Compute factorial(2)...\n"
"#     Task B: Compute factorial(2)...\n"
"#     Task C: Compute factorial(2)...\n"
"#     Task A: factorial(2) = 2\n"
"#     Task B: Compute factorial(3)...\n"
"#     Task C: Compute factorial(3)...\n"
"#     Task B: factorial(3) = 6\n"
"#     Task C: Compute factorial(4)...\n"
"#     Task C: factorial(4) = 24"
msgstr ""

#: ../../../library/asyncio-task.rst:389
msgid ""
"If *return_exceptions* is False, cancelling gather() after it has been "
"marked done won't cancel any submitted awaitables. For instance, gather can "
"be marked done after propagating an exception to the caller, therefore, "
"calling ``gather.cancel()`` after catching an exception (raised by one of "
"the awaitables) from gather won't cancel any other awaitables."
msgstr ""

#: ../../../library/asyncio-task.rst:396
msgid ""
"If the *gather* itself is cancelled, the cancellation is propagated "
"regardless of *return_exceptions*."
msgstr ""

#: ../../../library/asyncio-task.rst:402
msgid "Shielding From Cancellation"
msgstr ""

#: ../../../library/asyncio-task.rst:406
msgid ""
"Protect an :ref:`awaitable object <asyncio-awaitables>` from being :meth:"
"`cancelled <Task.cancel>`."
msgstr ""

#: ../../../library/asyncio-task.rst:409 ../../../library/asyncio-task.rst:449
msgid "If *aw* is a coroutine it is automatically scheduled as a Task."
msgstr ""

#: ../../../library/asyncio-task.rst:411
msgid "The statement::"
msgstr ""

#: ../../../library/asyncio-task.rst:413
msgid "res = await shield(something())"
msgstr ""

#: ../../../library/asyncio-task.rst:415
msgid "is equivalent to::"
msgstr ""

#: ../../../library/asyncio-task.rst:417
msgid "res = await something()"
msgstr ""

#: ../../../library/asyncio-task.rst:419
msgid ""
"*except* that if the coroutine containing it is cancelled, the Task running "
"in ``something()`` is not cancelled.  From the point of view of "
"``something()``, the cancellation did not happen. Although its caller is "
"still cancelled, so the \"await\" expression still raises a :exc:"
"`CancelledError`."
msgstr ""

#: ../../../library/asyncio-task.rst:425
msgid ""
"If ``something()`` is cancelled by other means (i.e. from within itself) "
"that would also cancel ``shield()``."
msgstr ""

#: ../../../library/asyncio-task.rst:428
msgid ""
"If it is desired to completely ignore cancellation (not recommended) the "
"``shield()`` function should be combined with a try/except clause, as "
"follows::"
msgstr ""

#: ../../../library/asyncio-task.rst:432
msgid ""
"try:\n"
"    res = await shield(something())\n"
"except CancelledError:\n"
"    res = None"
msgstr ""

#: ../../../library/asyncio-task.rst:442
msgid "Timeouts"
msgstr ""

#: ../../../library/asyncio-task.rst:446
msgid ""
"Wait for the *aw* :ref:`awaitable <asyncio-awaitables>` to complete with a "
"timeout."
msgstr ""

#: ../../../library/asyncio-task.rst:451
msgid ""
"*timeout* can either be ``None`` or a float or int number of seconds to wait "
"for.  If *timeout* is ``None``, block until the future completes."
msgstr ""

#: ../../../library/asyncio-task.rst:455
msgid ""
"If a timeout occurs, it cancels the task and raises :exc:`asyncio."
"TimeoutError`."
msgstr ""

#: ../../../library/asyncio-task.rst:458
msgid ""
"To avoid the task :meth:`cancellation <Task.cancel>`, wrap it in :func:"
"`shield`."
msgstr ""

#: ../../../library/asyncio-task.rst:461
msgid ""
"The function will wait until the future is actually cancelled, so the total "
"wait time may exceed the *timeout*."
msgstr ""

#: ../../../library/asyncio-task.rst:464
msgid "If the wait is cancelled, the future *aw* is also cancelled."
msgstr ""

#: ../../../library/asyncio-task.rst:473
msgid ""
"async def eternity():\n"
"    # Sleep for one hour\n"
"    await asyncio.sleep(3600)\n"
"    print('yay!')\n"
"\n"
"async def main():\n"
"    # Wait for at most 1 second\n"
"    try:\n"
"        await asyncio.wait_for(eternity(), timeout=1.0)\n"
"    except asyncio.TimeoutError:\n"
"        print('timeout!')\n"
"\n"
"asyncio.run(main())\n"
"\n"
"# Expected output:\n"
"#\n"
"#     timeout!"
msgstr ""

#: ../../../library/asyncio-task.rst:491
msgid ""
"When *aw* is cancelled due to a timeout, ``wait_for`` waits for *aw* to be "
"cancelled.  Previously, it raised :exc:`asyncio.TimeoutError` immediately."
msgstr ""

#: ../../../library/asyncio-task.rst:498
msgid "Waiting Primitives"
msgstr ""

#: ../../../library/asyncio-task.rst:503
msgid ""
"Run :ref:`awaitable objects <asyncio-awaitables>` in the *aws* iterable "
"concurrently and block until the condition specified by *return_when*."
msgstr ""

#: ../../../library/asyncio-task.rst:507
msgid "Returns two sets of Tasks/Futures: ``(done, pending)``."
msgstr ""

#: ../../../library/asyncio-task.rst:509
msgid "Usage::"
msgstr ""

#: ../../../library/asyncio-task.rst:511
msgid "done, pending = await asyncio.wait(aws)"
msgstr ""

#: ../../../library/asyncio-task.rst:513
msgid ""
"*timeout* (a float or int), if specified, can be used to control the maximum "
"number of seconds to wait before returning."
msgstr ""

#: ../../../library/asyncio-task.rst:516
msgid ""
"Note that this function does not raise :exc:`asyncio.TimeoutError`. Futures "
"or Tasks that aren't done when the timeout occurs are simply returned in the "
"second set."
msgstr ""

#: ../../../library/asyncio-task.rst:520
msgid ""
"*return_when* indicates when this function should return.  It must be one of "
"the following constants:"
msgstr ""

#: ../../../library/asyncio-task.rst:526
msgid "Constant"
msgstr ""

#: ../../../library/asyncio-task.rst:526
msgid "Description"
msgstr ""

#: ../../../library/asyncio-task.rst:528
msgid ":const:`FIRST_COMPLETED`"
msgstr ""

#: ../../../library/asyncio-task.rst:528
msgid "The function will return when any future finishes or is cancelled."
msgstr ""

#: ../../../library/asyncio-task.rst:531
msgid ":const:`FIRST_EXCEPTION`"
msgstr ""

#: ../../../library/asyncio-task.rst:531
msgid ""
"The function will return when any future finishes by raising an exception.  "
"If no future raises an exception then it is equivalent to :const:"
"`ALL_COMPLETED`."
msgstr ""

#: ../../../library/asyncio-task.rst:537
msgid ":const:`ALL_COMPLETED`"
msgstr ""

#: ../../../library/asyncio-task.rst:537
msgid "The function will return when all futures finish or are cancelled."
msgstr ""

#: ../../../library/asyncio-task.rst:541
msgid ""
"Unlike :func:`~asyncio.wait_for`, ``wait()`` does not cancel the futures "
"when a timeout occurs."
msgstr ""

#: ../../../library/asyncio-task.rst:546
msgid ""
"If any awaitable in *aws* is a coroutine, it is automatically scheduled as a "
"Task.  Passing coroutines objects to ``wait()`` directly is deprecated as it "
"leads to :ref:`confusing behavior <asyncio_example_wait_coroutine>`."
msgstr ""

#: ../../../library/asyncio-task.rst:558
msgid ""
"``wait()`` schedules coroutines as Tasks automatically and later returns "
"those implicitly created Task objects in ``(done, pending)`` sets.  "
"Therefore the following code won't work as expected::"
msgstr ""

#: ../../../library/asyncio-task.rst:562
msgid ""
"async def foo():\n"
"    return 42\n"
"\n"
"coro = foo()\n"
"done, pending = await asyncio.wait({coro})\n"
"\n"
"if coro in done:\n"
"    # This branch will never be run!"
msgstr ""

#: ../../../library/asyncio-task.rst:571
msgid "Here is how the above snippet can be fixed::"
msgstr ""

#: ../../../library/asyncio-task.rst:573
msgid ""
"async def foo():\n"
"    return 42\n"
"\n"
"task = asyncio.create_task(foo())\n"
"done, pending = await asyncio.wait({task})\n"
"\n"
"if task in done:\n"
"    # Everything will work as expected now."
msgstr ""

#: ../../../library/asyncio-task.rst:584
msgid "Passing coroutine objects to ``wait()`` directly is deprecated."
msgstr ""

#: ../../../library/asyncio-task.rst:590
msgid ""
"Run :ref:`awaitable objects <asyncio-awaitables>` in the *aws* iterable "
"concurrently.  Return an iterator of coroutines. Each coroutine returned can "
"be awaited to get the earliest next result from the iterable of the "
"remaining awaitables."
msgstr ""

#: ../../../library/asyncio-task.rst:595
msgid ""
"Raises :exc:`asyncio.TimeoutError` if the timeout occurs before all Futures "
"are done."
msgstr ""

#: ../../../library/asyncio-task.rst:603
msgid ""
"for coro in as_completed(aws):\n"
"    earliest_result = await coro\n"
"    # ..."
msgstr ""

#: ../../../library/asyncio-task.rst:609
msgid "Scheduling From Other Threads"
msgstr ""

#: ../../../library/asyncio-task.rst:613
msgid "Submit a coroutine to the given event loop.  Thread-safe."
msgstr ""

#: ../../../library/asyncio-task.rst:615
msgid ""
"Return a :class:`concurrent.futures.Future` to wait for the result from "
"another OS thread."
msgstr ""

#: ../../../library/asyncio-task.rst:618
msgid ""
"This function is meant to be called from a different OS thread than the one "
"where the event loop is running.  Example::"
msgstr ""

#: ../../../library/asyncio-task.rst:621
msgid ""
"# Create a coroutine\n"
"coro = asyncio.sleep(1, result=3)\n"
"\n"
"# Submit the coroutine to a given loop\n"
"future = asyncio.run_coroutine_threadsafe(coro, loop)\n"
"\n"
"# Wait for the result with an optional timeout argument\n"
"assert future.result(timeout) == 3"
msgstr ""

#: ../../../library/asyncio-task.rst:630
msgid ""
"If an exception is raised in the coroutine, the returned Future will be "
"notified.  It can also be used to cancel the task in the event loop::"
msgstr ""

#: ../../../library/asyncio-task.rst:634
msgid ""
"try:\n"
"    result = future.result(timeout)\n"
"except asyncio.TimeoutError:\n"
"    print('The coroutine took too long, cancelling the task...')\n"
"    future.cancel()\n"
"except Exception as exc:\n"
"    print(f'The coroutine raised an exception: {exc!r}')\n"
"else:\n"
"    print(f'The coroutine returned: {result!r}')"
msgstr ""

#: ../../../library/asyncio-task.rst:644
msgid ""
"See the :ref:`concurrency and multithreading <asyncio-multithreading>` "
"section of the documentation."
msgstr ""

#: ../../../library/asyncio-task.rst:647
msgid ""
"Unlike other asyncio functions this function requires the *loop* argument to "
"be passed explicitly."
msgstr ""

#: ../../../library/asyncio-task.rst:654
msgid "Introspection"
msgstr ""

#: ../../../library/asyncio-task.rst:659
msgid ""
"Return the currently running :class:`Task` instance, or ``None`` if no task "
"is running."
msgstr ""

#: ../../../library/asyncio-task.rst:662
msgid ""
"If *loop* is ``None`` :func:`get_running_loop` is used to get the current "
"loop."
msgstr ""

#: ../../../library/asyncio-task.rst:670
msgid "Return a set of not yet finished :class:`Task` objects run by the loop."
msgstr ""

#: ../../../library/asyncio-task.rst:673
msgid ""
"If *loop* is ``None``, :func:`get_running_loop` is used for getting current "
"loop."
msgstr ""

#: ../../../library/asyncio-task.rst:680
msgid "Task Object"
msgstr ""

#: ../../../library/asyncio-task.rst:684
msgid ""
"A :class:`Future-like <Future>` object that runs a Python :ref:`coroutine "
"<coroutine>`.  Not thread-safe."
msgstr ""

#: ../../../library/asyncio-task.rst:687
msgid ""
"Tasks are used to run coroutines in event loops. If a coroutine awaits on a "
"Future, the Task suspends the execution of the coroutine and waits for the "
"completion of the Future.  When the Future is *done*, the execution of the "
"wrapped coroutine resumes."
msgstr ""

#: ../../../library/asyncio-task.rst:693
msgid ""
"Event loops use cooperative scheduling: an event loop runs one Task at a "
"time.  While a Task awaits for the completion of a Future, the event loop "
"runs other Tasks, callbacks, or performs IO operations."
msgstr ""

#: ../../../library/asyncio-task.rst:698
msgid ""
"Use the high-level :func:`asyncio.create_task` function to create Tasks, or "
"the low-level :meth:`loop.create_task` or :func:`ensure_future` functions.  "
"Manual instantiation of Tasks is discouraged."
msgstr ""

#: ../../../library/asyncio-task.rst:703
msgid ""
"To cancel a running Task use the :meth:`cancel` method.  Calling it will "
"cause the Task to throw a :exc:`CancelledError` exception into the wrapped "
"coroutine.  If a coroutine is awaiting on a Future object during "
"cancellation, the Future object will be cancelled."
msgstr ""

#: ../../../library/asyncio-task.rst:708
msgid ""
":meth:`cancelled` can be used to check if the Task was cancelled. The method "
"returns ``True`` if the wrapped coroutine did not suppress the :exc:"
"`CancelledError` exception and was actually cancelled."
msgstr ""

#: ../../../library/asyncio-task.rst:713
msgid ""
":class:`asyncio.Task` inherits from :class:`Future` all of its APIs except :"
"meth:`Future.set_result` and :meth:`Future.set_exception`."
msgstr ""

#: ../../../library/asyncio-task.rst:717
msgid ""
"Tasks support the :mod:`contextvars` module.  When a Task is created it "
"copies the current context and later runs its coroutine in the copied "
"context."
msgstr ""

#: ../../../library/asyncio-task.rst:721
msgid "Added support for the :mod:`contextvars` module."
msgstr ""

#: ../../../library/asyncio-task.rst:732
msgid "Request the Task to be cancelled."
msgstr ""

#: ../../../library/asyncio-task.rst:734
msgid ""
"This arranges for a :exc:`CancelledError` exception to be thrown into the "
"wrapped coroutine on the next cycle of the event loop."
msgstr ""

#: ../../../library/asyncio-task.rst:737
msgid ""
"The coroutine then has a chance to clean up or even deny the request by "
"suppressing the exception with a :keyword:`try` ... ... ``except "
"CancelledError`` ... :keyword:`finally` block. Therefore, unlike :meth:"
"`Future.cancel`, :meth:`Task.cancel` does not guarantee that the Task will "
"be cancelled, although suppressing cancellation completely is not common and "
"is actively discouraged."
msgstr ""

#: ../../../library/asyncio-task.rst:747
msgid ""
"The following example illustrates how coroutines can intercept the "
"cancellation request::"
msgstr ""

#: ../../../library/asyncio-task.rst:750
msgid ""
"async def cancel_me():\n"
"    print('cancel_me(): before sleep')\n"
"\n"
"    try:\n"
"        # Wait for 1 hour\n"
"        await asyncio.sleep(3600)\n"
"    except asyncio.CancelledError:\n"
"        print('cancel_me(): cancel sleep')\n"
"        raise\n"
"    finally:\n"
"        print('cancel_me(): after sleep')\n"
"\n"
"async def main():\n"
"    # Create a \"cancel_me\" Task\n"
"    task = asyncio.create_task(cancel_me())\n"
"\n"
"    # Wait for 1 second\n"
"    await asyncio.sleep(1)\n"
"\n"
"    task.cancel()\n"
"    try:\n"
"        await task\n"
"    except asyncio.CancelledError:\n"
"        print(\"main(): cancel_me is cancelled now\")\n"
"\n"
"asyncio.run(main())\n"
"\n"
"# Expected output:\n"
"#\n"
"#     cancel_me(): before sleep\n"
"#     cancel_me(): cancel sleep\n"
"#     cancel_me(): after sleep\n"
"#     main(): cancel_me is cancelled now"
msgstr ""

#: ../../../library/asyncio-task.rst:786
msgid "Return ``True`` if the Task is *cancelled*."
msgstr ""

#: ../../../library/asyncio-task.rst:788
msgid ""
"The Task is *cancelled* when the cancellation was requested with :meth:"
"`cancel` and the wrapped coroutine propagated the :exc:`CancelledError` "
"exception thrown into it."
msgstr ""

#: ../../../library/asyncio-task.rst:794
msgid "Return ``True`` if the Task is *done*."
msgstr ""

#: ../../../library/asyncio-task.rst:796
msgid ""
"A Task is *done* when the wrapped coroutine either returned a value, raised "
"an exception, or the Task was cancelled."
msgstr ""

#: ../../../library/asyncio-task.rst:801
msgid "Return the result of the Task."
msgstr ""

#: ../../../library/asyncio-task.rst:803
msgid ""
"If the Task is *done*, the result of the wrapped coroutine is returned (or "
"if the coroutine raised an exception, that exception is re-raised.)"
msgstr ""

#: ../../../library/asyncio-task.rst:807 ../../../library/asyncio-task.rst:821
msgid ""
"If the Task has been *cancelled*, this method raises a :exc:`CancelledError` "
"exception."
msgstr ""

#: ../../../library/asyncio-task.rst:810
msgid ""
"If the Task's result isn't yet available, this method raises a :exc:"
"`InvalidStateError` exception."
msgstr ""

#: ../../../library/asyncio-task.rst:815
msgid "Return the exception of the Task."
msgstr ""

#: ../../../library/asyncio-task.rst:817
msgid ""
"If the wrapped coroutine raised an exception that exception is returned.  If "
"the wrapped coroutine returned normally this method returns ``None``."
msgstr ""

#: ../../../library/asyncio-task.rst:824
msgid ""
"If the Task isn't *done* yet, this method raises an :exc:`InvalidStateError` "
"exception."
msgstr ""

#: ../../../library/asyncio-task.rst:829
msgid "Add a callback to be run when the Task is *done*."
msgstr ""

#: ../../../library/asyncio-task.rst:831 ../../../library/asyncio-task.rst:840
msgid "This method should only be used in low-level callback-based code."
msgstr ""

#: ../../../library/asyncio-task.rst:833
msgid ""
"See the documentation of :meth:`Future.add_done_callback` for more details."
msgstr ""

#: ../../../library/asyncio-task.rst:838
msgid "Remove *callback* from the callbacks list."
msgstr ""

#: ../../../library/asyncio-task.rst:842
msgid ""
"See the documentation of :meth:`Future.remove_done_callback` for more "
"details."
msgstr ""

#: ../../../library/asyncio-task.rst:847
msgid "Return the list of stack frames for this Task."
msgstr ""

#: ../../../library/asyncio-task.rst:849
msgid ""
"If the wrapped coroutine is not done, this returns the stack where it is "
"suspended.  If the coroutine has completed successfully or was cancelled, "
"this returns an empty list. If the coroutine was terminated by an exception, "
"this returns the list of traceback frames."
msgstr ""

#: ../../../library/asyncio-task.rst:855
msgid "The frames are always ordered from oldest to newest."
msgstr ""

#: ../../../library/asyncio-task.rst:857
msgid "Only one stack frame is returned for a suspended coroutine."
msgstr ""

#: ../../../library/asyncio-task.rst:859
msgid ""
"The optional *limit* argument sets the maximum number of frames to return; "
"by default all available frames are returned. The ordering of the returned "
"list differs depending on whether a stack or a traceback is returned: the "
"newest frames of a stack are returned, but the oldest frames of a traceback "
"are returned.  (This matches the behavior of the traceback module.)"
msgstr ""

#: ../../../library/asyncio-task.rst:868
msgid "Print the stack or traceback for this Task."
msgstr ""

#: ../../../library/asyncio-task.rst:870
msgid ""
"This produces output similar to that of the traceback module for the frames "
"retrieved by :meth:`get_stack`."
msgstr ""

#: ../../../library/asyncio-task.rst:873
msgid "The *limit* argument is passed to :meth:`get_stack` directly."
msgstr ""

#: ../../../library/asyncio-task.rst:875
msgid ""
"The *file* argument is an I/O stream to which the output is written; by "
"default output is written to :data:`sys.stderr`."
msgstr ""

#: ../../../library/asyncio-task.rst:880
msgid "Return the coroutine object wrapped by the :class:`Task`."
msgstr ""

#: ../../../library/asyncio-task.rst:886
msgid "Return the name of the Task."
msgstr ""

#: ../../../library/asyncio-task.rst:888
msgid ""
"If no name has been explicitly assigned to the Task, the default asyncio "
"Task implementation generates a default name during instantiation."
msgstr ""

#: ../../../library/asyncio-task.rst:896
msgid "Set the name of the Task."
msgstr ""

#: ../../../library/asyncio-task.rst:898
msgid ""
"The *value* argument can be any object, which is then converted to a string."
msgstr ""

#: ../../../library/asyncio-task.rst:901
msgid ""
"In the default Task implementation, the name will be visible in the :func:"
"`repr` output of a task object."
msgstr ""

#: ../../../library/asyncio-task.rst:908
msgid "Return a set of all tasks for an event loop."
msgstr ""

#: ../../../library/asyncio-task.rst:910
msgid ""
"By default all tasks for the current event loop are returned. If *loop* is "
"``None``, the :func:`get_event_loop` function is used to get the current "
"loop."
msgstr ""

#: ../../../library/asyncio-task.rst:916
msgid ""
"Do not call this as a task method. Use the :func:`asyncio.all_tasks` "
"function instead."
msgstr ""

#: ../../../library/asyncio-task.rst:921
msgid "Return the currently running task or ``None``."
msgstr ""

#: ../../../library/asyncio-task.rst:923
msgid ""
"If *loop* is ``None``, the :func:`get_event_loop` function is used to get "
"the current loop."
msgstr ""

#: ../../../library/asyncio-task.rst:928
msgid ""
"Do not call this as a task method.  Use the :func:`asyncio.current_task` "
"function instead."
msgstr ""

#: ../../../library/asyncio-task.rst:935
msgid "Generator-based Coroutines"
msgstr ""

#: ../../../library/asyncio-task.rst:939
msgid ""
"Support for generator-based coroutines is **deprecated** and is scheduled "
"for removal in Python 3.10."
msgstr ""

#: ../../../library/asyncio-task.rst:942
msgid ""
"Generator-based coroutines predate async/await syntax.  They are Python "
"generators that use ``yield from`` expressions to await on Futures and other "
"coroutines."
msgstr ""

#: ../../../library/asyncio-task.rst:946
msgid ""
"Generator-based coroutines should be decorated with :func:`@asyncio."
"coroutine <asyncio.coroutine>`, although this is not enforced."
msgstr ""

#: ../../../library/asyncio-task.rst:953
msgid "Decorator to mark generator-based coroutines."
msgstr ""

#: ../../../library/asyncio-task.rst:955
msgid ""
"This decorator enables legacy generator-based coroutines to be compatible "
"with async/await code::"
msgstr ""

#: ../../../library/asyncio-task.rst:958
msgid ""
"@asyncio.coroutine\n"
"def old_style_coroutine():\n"
"    yield from asyncio.sleep(1)\n"
"\n"
"async def main():\n"
"    await old_style_coroutine()"
msgstr ""

#: ../../../library/asyncio-task.rst:965
msgid "This decorator should not be used for :keyword:`async def` coroutines."
msgstr ""

#: ../../../library/asyncio-task.rst:970
msgid "Use :keyword:`async def` instead."
msgstr ""

#: ../../../library/asyncio-task.rst:974
msgid "Return ``True`` if *obj* is a :ref:`coroutine object <coroutine>`."
msgstr ""

#: ../../../library/asyncio-task.rst:976
msgid ""
"This method is different from :func:`inspect.iscoroutine` because it returns "
"``True`` for generator-based coroutines."
msgstr ""

#: ../../../library/asyncio-task.rst:981
msgid "Return ``True`` if *func* is a :ref:`coroutine function <coroutine>`."
msgstr ""

#: ../../../library/asyncio-task.rst:984
msgid ""
"This method is different from :func:`inspect.iscoroutinefunction` because it "
"returns ``True`` for generator-based coroutine functions decorated with :"
"func:`@coroutine <coroutine>`."
msgstr ""
