# SOME DESCRIPTIVE TITLE.
# Copyright (C) 1990-2025, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.1\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-08-11 04:41+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: zh_CN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../../../c-api/exceptions.rst:8
msgid "Exception Handling"
msgstr ""

#: ../../../c-api/exceptions.rst:10
msgid ""
"The functions described in this chapter will let you handle and raise Python "
"exceptions.  It is important to understand some of the basics of Python "
"exception handling.  It works somewhat like the Unix :cdata:`errno` "
"variable: there is a global indicator (per thread) of the last error that "
"occurred.  Most functions don't clear this on success, but will set it to "
"indicate the cause of the error on failure.  Most functions also return an "
"error indicator, usually *NULL* if they are supposed to return a pointer, or "
"``-1`` if they return an integer (exception: the :cfunc:`PyArg_\\*` "
"functions return ``1`` for success and ``0`` for failure)."
msgstr ""

#: ../../../c-api/exceptions.rst:20
msgid ""
"When a function must fail because some function it called failed, it "
"generally doesn't set the error indicator; the function it called already "
"set it.  It is responsible for either handling the error and clearing the "
"exception or returning after cleaning up any resources it holds (such as "
"object references or memory allocations); it should *not* continue normally "
"if it is not prepared to handle the error.  If returning due to an error, it "
"is important to indicate to the caller that an error has been set.  If the "
"error is not handled or carefully propagated, additional calls into the "
"Python/C API may not behave as intended and may fail in mysterious ways."
msgstr ""

#: ../../../c-api/exceptions.rst:30
msgid ""
"The error indicator consists of three Python objects corresponding to the "
"result of ``sys.exc_info()``.  API functions exist to interact with the "
"error indicator in various ways.  There is a separate error indicator for "
"each thread."
msgstr ""

#: ../../../c-api/exceptions.rst:351
msgid "Exception Objects"
msgstr ""

#: ../../../c-api/exceptions.rst:399
msgid "Unicode Exception Objects"
msgstr ""

#: ../../../c-api/exceptions.rst:401
msgid ""
"The following functions are used to create and modify Unicode exceptions "
"from C."
msgstr ""

#: ../../../c-api/exceptions.rst:474
msgid "Recursion Control"
msgstr ""

#: ../../../c-api/exceptions.rst:476
msgid ""
"These two functions provide a way to perform safe recursive calls at the C "
"level, both in the core and in extension modules.  They are needed if the "
"recursive code does not necessarily invoke Python code (which tracks its "
"recursion depth automatically)."
msgstr ""

#: ../../../c-api/exceptions.rst:506
msgid "Standard Exceptions"
msgstr ""

#: ../../../c-api/exceptions.rst:508
msgid ""
"All standard Python exceptions are available as global variables whose names "
"are ``PyExc_`` followed by the Python exception name.  These have the type :"
"ctype:`PyObject\\*`; they are all class objects.  For completeness, here are "
"all the variables:"
msgstr ""

#: ../../../c-api/exceptions.rst:514
msgid "C Name"
msgstr ""

#: ../../../c-api/exceptions.rst:514
msgid "Python Name"
msgstr ""

#: ../../../c-api/exceptions.rst:514
msgid "Notes"
msgstr ""

#: ../../../c-api/exceptions.rst:516
msgid ":cdata:`PyExc_BaseException`"
msgstr ""

#: ../../../c-api/exceptions.rst:516
msgid ":exc:`BaseException`"
msgstr ""

#: ../../../c-api/exceptions.rst:516 ../../../c-api/exceptions.rst:518
#: ../../../c-api/exceptions.rst:520 ../../../c-api/exceptions.rst:522
#: ../../../c-api/exceptions.rst:530
msgid "\\(1)"
msgstr ""

#: ../../../c-api/exceptions.rst:518
msgid ":cdata:`PyExc_Exception`"
msgstr ""

#: ../../../c-api/exceptions.rst:518
msgid ":exc:`Exception`"
msgstr ""

#: ../../../c-api/exceptions.rst:520
msgid ":cdata:`PyExc_ArithmeticError`"
msgstr ""

#: ../../../c-api/exceptions.rst:520
msgid ":exc:`ArithmeticError`"
msgstr ""

#: ../../../c-api/exceptions.rst:522
msgid ":cdata:`PyExc_LookupError`"
msgstr ""

#: ../../../c-api/exceptions.rst:522
msgid ":exc:`LookupError`"
msgstr ""

#: ../../../c-api/exceptions.rst:524
msgid ":cdata:`PyExc_AssertionError`"
msgstr ""

#: ../../../c-api/exceptions.rst:524
msgid ":exc:`AssertionError`"
msgstr ""

#: ../../../c-api/exceptions.rst:526
msgid ":cdata:`PyExc_AttributeError`"
msgstr ""

#: ../../../c-api/exceptions.rst:526
msgid ":exc:`AttributeError`"
msgstr ""

#: ../../../c-api/exceptions.rst:528
msgid ":cdata:`PyExc_EOFError`"
msgstr ""

#: ../../../c-api/exceptions.rst:528
msgid ":exc:`EOFError`"
msgstr ""

#: ../../../c-api/exceptions.rst:530
msgid ":cdata:`PyExc_EnvironmentError`"
msgstr ""

#: ../../../c-api/exceptions.rst:530
msgid ":exc:`EnvironmentError`"
msgstr ""

#: ../../../c-api/exceptions.rst:532
msgid ":cdata:`PyExc_FloatingPointError`"
msgstr ""

#: ../../../c-api/exceptions.rst:532
msgid ":exc:`FloatingPointError`"
msgstr ""

#: ../../../c-api/exceptions.rst:534
msgid ":cdata:`PyExc_IOError`"
msgstr ""

#: ../../../c-api/exceptions.rst:534
msgid ":exc:`IOError`"
msgstr ""

#: ../../../c-api/exceptions.rst:536
msgid ":cdata:`PyExc_ImportError`"
msgstr ""

#: ../../../c-api/exceptions.rst:536
msgid ":exc:`ImportError`"
msgstr ""

#: ../../../c-api/exceptions.rst:538
msgid ":cdata:`PyExc_IndexError`"
msgstr ""

#: ../../../c-api/exceptions.rst:538
msgid ":exc:`IndexError`"
msgstr ""

#: ../../../c-api/exceptions.rst:540
msgid ":cdata:`PyExc_KeyError`"
msgstr ""

#: ../../../c-api/exceptions.rst:540
msgid ":exc:`KeyError`"
msgstr ""

#: ../../../c-api/exceptions.rst:542
msgid ":cdata:`PyExc_KeyboardInterrupt`"
msgstr ""

#: ../../../c-api/exceptions.rst:542
msgid ":exc:`KeyboardInterrupt`"
msgstr ""

#: ../../../c-api/exceptions.rst:544
msgid ":cdata:`PyExc_MemoryError`"
msgstr ""

#: ../../../c-api/exceptions.rst:544
msgid ":exc:`MemoryError`"
msgstr ""

#: ../../../c-api/exceptions.rst:546
msgid ":cdata:`PyExc_NameError`"
msgstr ""

#: ../../../c-api/exceptions.rst:546
msgid ":exc:`NameError`"
msgstr ""

#: ../../../c-api/exceptions.rst:548
msgid ":cdata:`PyExc_NotImplementedError`"
msgstr ""

#: ../../../c-api/exceptions.rst:548
msgid ":exc:`NotImplementedError`"
msgstr ""

#: ../../../c-api/exceptions.rst:550
msgid ":cdata:`PyExc_OSError`"
msgstr ""

#: ../../../c-api/exceptions.rst:550
msgid ":exc:`OSError`"
msgstr ""

#: ../../../c-api/exceptions.rst:552
msgid ":cdata:`PyExc_OverflowError`"
msgstr ""

#: ../../../c-api/exceptions.rst:552
msgid ":exc:`OverflowError`"
msgstr ""

#: ../../../c-api/exceptions.rst:554
msgid ":cdata:`PyExc_ReferenceError`"
msgstr ""

#: ../../../c-api/exceptions.rst:554
msgid ":exc:`ReferenceError`"
msgstr ""

#: ../../../c-api/exceptions.rst:554
msgid "\\(2)"
msgstr ""

#: ../../../c-api/exceptions.rst:556
msgid ":cdata:`PyExc_RuntimeError`"
msgstr ""

#: ../../../c-api/exceptions.rst:556
msgid ":exc:`RuntimeError`"
msgstr ""

#: ../../../c-api/exceptions.rst:558
msgid ":cdata:`PyExc_SyntaxError`"
msgstr ""

#: ../../../c-api/exceptions.rst:558
msgid ":exc:`SyntaxError`"
msgstr ""

#: ../../../c-api/exceptions.rst:560
msgid ":cdata:`PyExc_SystemError`"
msgstr ""

#: ../../../c-api/exceptions.rst:560
msgid ":exc:`SystemError`"
msgstr ""

#: ../../../c-api/exceptions.rst:562
msgid ":cdata:`PyExc_SystemExit`"
msgstr ""

#: ../../../c-api/exceptions.rst:562
msgid ":exc:`SystemExit`"
msgstr ""

#: ../../../c-api/exceptions.rst:564
msgid ":cdata:`PyExc_TypeError`"
msgstr ""

#: ../../../c-api/exceptions.rst:564
msgid ":exc:`TypeError`"
msgstr ""

#: ../../../c-api/exceptions.rst:566
msgid ":cdata:`PyExc_ValueError`"
msgstr ""

#: ../../../c-api/exceptions.rst:566
msgid ":exc:`ValueError`"
msgstr ""

#: ../../../c-api/exceptions.rst:568
msgid ":cdata:`PyExc_WindowsError`"
msgstr ""

#: ../../../c-api/exceptions.rst:568
msgid ":exc:`WindowsError`"
msgstr ""

#: ../../../c-api/exceptions.rst:568
msgid "\\(3)"
msgstr ""

#: ../../../c-api/exceptions.rst:570
msgid ":cdata:`PyExc_ZeroDivisionError`"
msgstr ""

#: ../../../c-api/exceptions.rst:570
msgid ":exc:`ZeroDivisionError`"
msgstr ""

#: ../../../c-api/exceptions.rst:603
msgid "Notes:"
msgstr ""

#: ../../../c-api/exceptions.rst:606
msgid "This is a base class for other standard exceptions."
msgstr ""

#: ../../../c-api/exceptions.rst:609
msgid "This is the same as :exc:`weakref.ReferenceError`."
msgstr ""

#: ../../../c-api/exceptions.rst:612
msgid ""
"Only defined on Windows; protect code that uses this by testing that the "
"preprocessor macro ``MS_WINDOWS`` is defined."
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_BaseException"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_Exception"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_ArithmeticError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_LookupError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_AssertionError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_AttributeError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_EOFError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_EnvironmentError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_FloatingPointError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_IOError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_ImportError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_IndexError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_KeyError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_KeyboardInterrupt"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_MemoryError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_NameError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_NotImplementedError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_OSError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_OverflowError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_ReferenceError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_RuntimeError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_SyntaxError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_SystemError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_SystemExit"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_TypeError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_ValueError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_WindowsError"
msgstr ""

#: ../../../c-api/exceptions.rst:573
msgid "PyExc_ZeroDivisionError"
msgstr ""
